from datetime import datetime, timezone
from pathlib import Path


def _section_list(title: str, items: list | str | None, fallback: str = "To be confirmed with ATI advisor.") -> list[str]:
    lines = [f"## {title}"]
    if isinstance(items, list) and items:
        lines.extend(f"- {item}" for item in items)
    elif isinstance(items, str) and items.strip():
        lines.append(items.strip())
    else:
        lines.append(fallback)
    return lines


def write_summary(client_folder: Path, state: dict) -> Path:
    """Generate summary.md from the final conversation state."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    name = state.get("client_name", "Unknown")
    session_id = state.get("session_id", "N/A")
    reqs = state.get("requirements", {})
    assets = state.get("assets", [])

    lines = [
        f"# CLIENT BRIEF — {name}",
        "**Generated by:** Client Onboarding Agent",
        f"**Date:** {now}",
        f"**Session ID:** {session_id}",
        "",
        "---",
        "",
        "## 1. Client Information",
        "| Field | Value |",
        "|-------|-------|",
        f"| Name | {name} |",
        f"| Contact Preference | {reqs.get('contact_preference', 'Not specified')} |",
        f"| Privacy Consent | Yes — {state.get('consent_ts', now)} |",
        "",
        "## 2. Project Overview",
        reqs.get("project_summary", "To be completed by ATI advisor."),
        "",
        "## 3. Requirements",
    ]

    for req in reqs.get("items", []):
        lines.append(f"- {req}")

    lines += [
        "",
        "## 4. Provided Assets",
        "| File | Description |",
        "|------|-------------|",
    ]
    asset_descriptions = state.get("asset_descriptions", {})
    for asset in assets:
        desc = asset_descriptions.get(asset, "Uploaded by client")
        lines.append(f"| {Path(asset).name} | {desc} |")

    recommended = reqs.get("recommended_services", "To be matched by ATI advisor.")
    if isinstance(recommended, list):
        services_text = "\n".join(f"- {s}" for s in recommended)
    else:
        services_text = str(recommended)

    lines += ["", "## 5. ATI Services Recommended", services_text, ""]
    lines += _section_list("6. Security Requirements", reqs.get("security_requirements"))
    lines.append("")
    lines += _section_list("7. Compliance & Regulatory", reqs.get("compliance_requirements"))
    lines.append("")
    lines += _section_list("8. Data Handling", reqs.get("data_handling"))
    lines.append("")
    lines += _section_list("9. Integration & Access", reqs.get("integration_access"))

    lines += [
        "",
        "## 10. Next Steps",
        "- [ ] ATI advisor review within 3 business days",
        "- [ ] NDA signing (1–2 business days)",
        "- [ ] Project scope & cost proposal (3–5 business days)",
        "",
        "---",
        "*Privacy questions: support@awesometechinc.com | 877-284-4968*",
        "*ATI Privacy Policy: https://awesometechinc.com/privacy-policy/*",
    ]

    summary_path = client_folder / "summary.md"
    summary_path.write_text("\n".join(lines), encoding="utf-8")
    return summary_path
